# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ledsampler.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_vlayout = QtWidgets.QVBoxLayout()
        self.main_vlayout.setSpacing(0)
        self.main_vlayout.setObjectName("main_vlayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(-1, 3, 9, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.mm_designing = QtWidgets.QPushButton(self.widget)
        self.mm_designing.setCheckable(True)
        self.mm_designing.setChecked(True)
        self.mm_designing.setAutoExclusive(True)
        self.mm_designing.setObjectName("mm_designing")
        self.horizontalLayout_6.addWidget(self.mm_designing)
        self.mm_linking = QtWidgets.QPushButton(self.widget)
        self.mm_linking.setCheckable(True)
        self.mm_linking.setAutoExclusive(True)
        self.mm_linking.setObjectName("mm_linking")
        self.horizontalLayout_6.addWidget(self.mm_linking)
        self.mm_editing = QtWidgets.QPushButton(self.widget)
        self.mm_editing.setCheckable(True)
        self.mm_editing.setAutoExclusive(True)
        self.mm_editing.setObjectName("mm_editing")
        self.horizontalLayout_6.addWidget(self.mm_editing)
        self.mm_exporting = QtWidgets.QPushButton(self.widget)
        self.mm_exporting.setCheckable(True)
        self.mm_exporting.setAutoExclusive(True)
        self.mm_exporting.setObjectName("mm_exporting")
        self.horizontalLayout_6.addWidget(self.mm_exporting)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.main_vlayout.addWidget(self.widget)
        self.line_mvu = QtWidgets.QFrame(self.centralwidget)
        self.line_mvu.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_mvu.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_mvu.setObjectName("line_mvu")
        self.main_vlayout.addWidget(self.line_mvu)
        self.label_viewport = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_viewport.sizePolicy().hasHeightForWidth())
        self.label_viewport.setSizePolicy(sizePolicy)
        self.label_viewport.setAutoFillBackground(False)
        self.label_viewport.setObjectName("label_viewport")
        self.main_vlayout.addWidget(self.label_viewport)
        self.line_mvc = QtWidgets.QFrame(self.centralwidget)
        self.line_mvc.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_mvc.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_mvc.setObjectName("line_mvc")
        self.main_vlayout.addWidget(self.line_mvc)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.hs_currframe = QtWidgets.QSlider(self.widget_2)
        self.hs_currframe.setMaximum(999)
        self.hs_currframe.setOrientation(QtCore.Qt.Horizontal)
        self.hs_currframe.setObjectName("hs_currframe")
        self.horizontalLayout_7.addWidget(self.hs_currframe)
        self.label_currframe = QtWidgets.QLabel(self.widget_2)
        self.label_currframe.setObjectName("label_currframe")
        self.horizontalLayout_7.addWidget(self.label_currframe)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.main_vlayout.addWidget(self.widget_2)
        self.line_mvb = QtWidgets.QFrame(self.centralwidget)
        self.line_mvb.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_mvb.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_mvb.setObjectName("line_mvb")
        self.main_vlayout.addWidget(self.line_mvb)
        self.horizontalLayout.addLayout(self.main_vlayout)
        self.line_cdiv = QtWidgets.QFrame(self.centralwidget)
        self.line_cdiv.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_cdiv.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_cdiv.setObjectName("line_cdiv")
        self.horizontalLayout.addWidget(self.line_cdiv)
        self.prop_vlayout = QtWidgets.QVBoxLayout()
        self.prop_vlayout.setSpacing(0)
        self.prop_vlayout.setObjectName("prop_vlayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_inspector = QtWidgets.QWidget()
        self.tab_inspector.setObjectName("tab_inspector")
        self.horizontalLayout_inspector = QtWidgets.QHBoxLayout(self.tab_inspector)
        self.horizontalLayout_inspector.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_inspector.setSpacing(0)
        self.horizontalLayout_inspector.setObjectName("horizontalLayout_inspector")
        self.tree_inspector = QtWidgets.QTreeWidget(self.tab_inspector)
        self.tree_inspector.setDragEnabled(False)
        self.tree_inspector.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tree_inspector.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tree_inspector.setObjectName("tree_inspector")
        self.horizontalLayout_inspector.addWidget(self.tree_inspector)
        self.tabWidget.addTab(self.tab_inspector, "")
        self.tab_linker = QtWidgets.QWidget()
        self.tab_linker.setObjectName("tab_linker")
        self.horizontalLayout_linker = QtWidgets.QHBoxLayout(self.tab_linker)
        self.horizontalLayout_linker.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_linker.setSpacing(0)
        self.horizontalLayout_linker.setObjectName("horizontalLayout_linker")
        self.tree_linker = QtWidgets.QTreeWidget(self.tab_linker)
        self.tree_linker.setObjectName("tree_linker")
        self.tree_linker.headerItem().setText(0, "Nodes")
        self.horizontalLayout_linker.addWidget(self.tree_linker)
        self.tabWidget.addTab(self.tab_linker, "")
        self.tab_sampler = QtWidgets.QWidget()
        self.tab_sampler.setObjectName("tab_sampler")
        self.horizontalLayout_sampler = QtWidgets.QHBoxLayout(self.tab_sampler)
        self.horizontalLayout_sampler.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_sampler.setSpacing(0)
        self.horizontalLayout_sampler.setObjectName("horizontalLayout_sampler")
        self.tree_sampler = QtWidgets.QTreeWidget(self.tab_sampler)
        self.tree_sampler.setObjectName("tree_sampler")
        self.tree_sampler.headerItem().setText(0, "Nodes")
        self.horizontalLayout_sampler.addWidget(self.tree_sampler)
        self.tabWidget.addTab(self.tab_sampler, "")
        self.tab_exporter = QtWidgets.QWidget()
        self.tab_exporter.setObjectName("tab_exporter")
        self.horizontalLayout_exporter = QtWidgets.QHBoxLayout(self.tab_exporter)
        self.horizontalLayout_exporter.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_exporter.setSpacing(0)
        self.horizontalLayout_exporter.setObjectName("horizontalLayout_exporter")
        self.tree_exporter = QtWidgets.QTreeWidget(self.tab_exporter)
        self.tree_exporter.setObjectName("tree_exporter")
        self.tree_exporter.headerItem().setText(0, "Nodes")
        self.horizontalLayout_exporter.addWidget(self.tree_exporter)
        self.tabWidget.addTab(self.tab_exporter, "")
        self.prop_vlayout.addWidget(self.tabWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.prop_vlayout.addWidget(self.line)
        self.label_prop = QtWidgets.QLabel(self.centralwidget)
        self.label_prop.setObjectName("label_prop")
        self.prop_vlayout.addWidget(self.label_prop)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.propertyWidget = QtWidgets.QWidget()
        self.propertyWidget.setGeometry(QtCore.QRect(0, 0, 323, 325))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyWidget.sizePolicy().hasHeightForWidth())
        self.propertyWidget.setSizePolicy(sizePolicy)
        self.propertyWidget.setObjectName("propertyWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.propertyWidget)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.propertyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(64, 64))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.label_5 = QtWidgets.QLabel(self.propertyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.propertyWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addLayout(self.formLayout)
        self.lineEdit = QtWidgets.QLineEdit(self.propertyWidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setFrame(True)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.comboBox = QtWidgets.QComboBox(self.propertyWidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.scrollArea.setWidget(self.propertyWidget)
        self.prop_vlayout.addWidget(self.scrollArea)
        self.prop_vlayout.setStretch(0, 1)
        self.prop_vlayout.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.prop_vlayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mm_designing.setText(_translate("MainWindow", "Designing"))
        self.mm_linking.setText(_translate("MainWindow", "Linking"))
        self.mm_editing.setText(_translate("MainWindow", "Editing"))
        self.mm_exporting.setText(_translate("MainWindow", "Exporting"))
        self.pushButton.setText(_translate("MainWindow", "Render Frame"))
        self.pushButton_2.setText(_translate("MainWindow", "Render All"))
        self.label_viewport.setText(_translate("MainWindow", "TextLabel"))
        self.label_currframe.setText(_translate("MainWindow", "1/10"))
        self.pushButton_6.setText(_translate("MainWindow", "L"))
        self.pushButton_5.setText(_translate("MainWindow", "P"))
        self.pushButton_4.setText(_translate("MainWindow", "R"))
        self.tree_inspector.headerItem().setText(0, _translate("MainWindow", "Nodes"))
        self.tree_inspector.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inspector), _translate("MainWindow", "Inspector"))
        self.tree_linker.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_linker), _translate("MainWindow", "Linker"))
        self.tree_sampler.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sampler), _translate("MainWindow", "Sampler"))
        self.tree_exporter.headerItem().setText(1, _translate("MainWindow", "Type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_exporter), _translate("MainWindow", "Exporter"))
        self.label_prop.setText(_translate("MainWindow", " Property"))
        self.label_5.setText(_translate("MainWindow", "Name"))
        self.label_6.setText(_translate("MainWindow", "Type"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuExport.setTitle(_translate("MainWindow", "Add Node"))
